/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PuestosGuardadosRouteImport } from './routes/puestos-guardados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpleosRouteImport } from './routes/empleos'
import { Route as CrearCvRouteImport } from './routes/crear-cv'
import { Route as ContactanosRouteImport } from './routes/contactanos'
import { Route as CargarCvRouteImport } from './routes/cargar-cv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpleosIndexRouteImport } from './routes/empleos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmpleosTecnicoPcRouteImport } from './routes/empleos.tecnico-pc'
import { Route as EmpleosRepositorRouteImport } from './routes/empleos.repositor'
import { Route as EmpleosOperadorRouteImport } from './routes/empleos.operador'
import { Route as EmpleosLimpiezaRouteImport } from './routes/empleos.limpieza'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPostulacionesRouteImport } from './routes/admin.postulaciones'
import { Route as AdminEstadisticasRouteImport } from './routes/admin.estadisticas'
import { Route as AdminEmpleosRouteImport } from './routes/admin.empleos'
import { Route as AdminCvsRouteImport } from './routes/admin.cvs'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PuestosGuardadosRoute = PuestosGuardadosRouteImport.update({
  id: '/puestos-guardados',
  path: '/puestos-guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleosRoute = EmpleosRouteImport.update({
  id: '/empleos',
  path: '/empleos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCvRoute = CrearCvRouteImport.update({
  id: '/crear-cv',
  path: '/crear-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactanosRoute = ContactanosRouteImport.update({
  id: '/contactanos',
  path: '/contactanos',
  getParentRoute: () => rootRouteImport,
} as any)
const CargarCvRoute = CargarCvRouteImport.update({
  id: '/cargar-cv',
  path: '/cargar-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleosIndexRoute = EmpleosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpleosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmpleosTecnicoPcRoute = EmpleosTecnicoPcRouteImport.update({
  id: '/tecnico-pc',
  path: '/tecnico-pc',
  getParentRoute: () => EmpleosRoute,
} as any)
const EmpleosRepositorRoute = EmpleosRepositorRouteImport.update({
  id: '/repositor',
  path: '/repositor',
  getParentRoute: () => EmpleosRoute,
} as any)
const EmpleosOperadorRoute = EmpleosOperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => EmpleosRoute,
} as any)
const EmpleosLimpiezaRoute = EmpleosLimpiezaRouteImport.update({
  id: '/limpieza',
  path: '/limpieza',
  getParentRoute: () => EmpleosRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostulacionesRoute = AdminPostulacionesRouteImport.update({
  id: '/postulaciones',
  path: '/postulaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstadisticasRoute = AdminEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpleosRoute = AdminEmpleosRouteImport.update({
  id: '/empleos',
  path: '/empleos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCvsRoute = AdminCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cargar-cv': typeof CargarCvRoute
  '/contactanos': typeof ContactanosRoute
  '/crear-cv': typeof CrearCvRoute
  '/empleos': typeof EmpleosRouteWithChildren
  '/login': typeof LoginRoute
  '/puestos-guardados': typeof PuestosGuardadosRoute
  '/register': typeof RegisterRoute
  '/admin/cvs': typeof AdminCvsRoute
  '/admin/empleos': typeof AdminEmpleosRoute
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/postulaciones': typeof AdminPostulacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empleos/limpieza': typeof EmpleosLimpiezaRoute
  '/empleos/operador': typeof EmpleosOperadorRoute
  '/empleos/repositor': typeof EmpleosRepositorRoute
  '/empleos/tecnico-pc': typeof EmpleosTecnicoPcRoute
  '/admin/': typeof AdminIndexRoute
  '/empleos/': typeof EmpleosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargar-cv': typeof CargarCvRoute
  '/contactanos': typeof ContactanosRoute
  '/crear-cv': typeof CrearCvRoute
  '/login': typeof LoginRoute
  '/puestos-guardados': typeof PuestosGuardadosRoute
  '/register': typeof RegisterRoute
  '/admin/cvs': typeof AdminCvsRoute
  '/admin/empleos': typeof AdminEmpleosRoute
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/postulaciones': typeof AdminPostulacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empleos/limpieza': typeof EmpleosLimpiezaRoute
  '/empleos/operador': typeof EmpleosOperadorRoute
  '/empleos/repositor': typeof EmpleosRepositorRoute
  '/empleos/tecnico-pc': typeof EmpleosTecnicoPcRoute
  '/admin': typeof AdminIndexRoute
  '/empleos': typeof EmpleosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cargar-cv': typeof CargarCvRoute
  '/contactanos': typeof ContactanosRoute
  '/crear-cv': typeof CrearCvRoute
  '/empleos': typeof EmpleosRouteWithChildren
  '/login': typeof LoginRoute
  '/puestos-guardados': typeof PuestosGuardadosRoute
  '/register': typeof RegisterRoute
  '/admin/cvs': typeof AdminCvsRoute
  '/admin/empleos': typeof AdminEmpleosRoute
  '/admin/estadisticas': typeof AdminEstadisticasRoute
  '/admin/postulaciones': typeof AdminPostulacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empleos/limpieza': typeof EmpleosLimpiezaRoute
  '/empleos/operador': typeof EmpleosOperadorRoute
  '/empleos/repositor': typeof EmpleosRepositorRoute
  '/empleos/tecnico-pc': typeof EmpleosTecnicoPcRoute
  '/admin/': typeof AdminIndexRoute
  '/empleos/': typeof EmpleosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cargar-cv'
    | '/contactanos'
    | '/crear-cv'
    | '/empleos'
    | '/login'
    | '/puestos-guardados'
    | '/register'
    | '/admin/cvs'
    | '/admin/empleos'
    | '/admin/estadisticas'
    | '/admin/postulaciones'
    | '/admin/usuarios'
    | '/empleos/limpieza'
    | '/empleos/operador'
    | '/empleos/repositor'
    | '/empleos/tecnico-pc'
    | '/admin/'
    | '/empleos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargar-cv'
    | '/contactanos'
    | '/crear-cv'
    | '/login'
    | '/puestos-guardados'
    | '/register'
    | '/admin/cvs'
    | '/admin/empleos'
    | '/admin/estadisticas'
    | '/admin/postulaciones'
    | '/admin/usuarios'
    | '/empleos/limpieza'
    | '/empleos/operador'
    | '/empleos/repositor'
    | '/empleos/tecnico-pc'
    | '/admin'
    | '/empleos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cargar-cv'
    | '/contactanos'
    | '/crear-cv'
    | '/empleos'
    | '/login'
    | '/puestos-guardados'
    | '/register'
    | '/admin/cvs'
    | '/admin/empleos'
    | '/admin/estadisticas'
    | '/admin/postulaciones'
    | '/admin/usuarios'
    | '/empleos/limpieza'
    | '/empleos/operador'
    | '/empleos/repositor'
    | '/empleos/tecnico-pc'
    | '/admin/'
    | '/empleos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CargarCvRoute: typeof CargarCvRoute
  ContactanosRoute: typeof ContactanosRoute
  CrearCvRoute: typeof CrearCvRoute
  EmpleosRoute: typeof EmpleosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PuestosGuardadosRoute: typeof PuestosGuardadosRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puestos-guardados': {
      id: '/puestos-guardados'
      path: '/puestos-guardados'
      fullPath: '/puestos-guardados'
      preLoaderRoute: typeof PuestosGuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleos': {
      id: '/empleos'
      path: '/empleos'
      fullPath: '/empleos'
      preLoaderRoute: typeof EmpleosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cv': {
      id: '/crear-cv'
      path: '/crear-cv'
      fullPath: '/crear-cv'
      preLoaderRoute: typeof CrearCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactanos': {
      id: '/contactanos'
      path: '/contactanos'
      fullPath: '/contactanos'
      preLoaderRoute: typeof ContactanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargar-cv': {
      id: '/cargar-cv'
      path: '/cargar-cv'
      fullPath: '/cargar-cv'
      preLoaderRoute: typeof CargarCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleos/': {
      id: '/empleos/'
      path: '/'
      fullPath: '/empleos/'
      preLoaderRoute: typeof EmpleosIndexRouteImport
      parentRoute: typeof EmpleosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/empleos/tecnico-pc': {
      id: '/empleos/tecnico-pc'
      path: '/tecnico-pc'
      fullPath: '/empleos/tecnico-pc'
      preLoaderRoute: typeof EmpleosTecnicoPcRouteImport
      parentRoute: typeof EmpleosRoute
    }
    '/empleos/repositor': {
      id: '/empleos/repositor'
      path: '/repositor'
      fullPath: '/empleos/repositor'
      preLoaderRoute: typeof EmpleosRepositorRouteImport
      parentRoute: typeof EmpleosRoute
    }
    '/empleos/operador': {
      id: '/empleos/operador'
      path: '/operador'
      fullPath: '/empleos/operador'
      preLoaderRoute: typeof EmpleosOperadorRouteImport
      parentRoute: typeof EmpleosRoute
    }
    '/empleos/limpieza': {
      id: '/empleos/limpieza'
      path: '/limpieza'
      fullPath: '/empleos/limpieza'
      preLoaderRoute: typeof EmpleosLimpiezaRouteImport
      parentRoute: typeof EmpleosRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/postulaciones': {
      id: '/admin/postulaciones'
      path: '/postulaciones'
      fullPath: '/admin/postulaciones'
      preLoaderRoute: typeof AdminPostulacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas': {
      id: '/admin/estadisticas'
      path: '/estadisticas'
      fullPath: '/admin/estadisticas'
      preLoaderRoute: typeof AdminEstadisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empleos': {
      id: '/admin/empleos'
      path: '/empleos'
      fullPath: '/admin/empleos'
      preLoaderRoute: typeof AdminEmpleosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cvs': {
      id: '/admin/cvs'
      path: '/cvs'
      fullPath: '/admin/cvs'
      preLoaderRoute: typeof AdminCvsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCvsRoute: typeof AdminCvsRoute
  AdminEmpleosRoute: typeof AdminEmpleosRoute
  AdminEstadisticasRoute: typeof AdminEstadisticasRoute
  AdminPostulacionesRoute: typeof AdminPostulacionesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCvsRoute: AdminCvsRoute,
  AdminEmpleosRoute: AdminEmpleosRoute,
  AdminEstadisticasRoute: AdminEstadisticasRoute,
  AdminPostulacionesRoute: AdminPostulacionesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmpleosRouteChildren {
  EmpleosLimpiezaRoute: typeof EmpleosLimpiezaRoute
  EmpleosOperadorRoute: typeof EmpleosOperadorRoute
  EmpleosRepositorRoute: typeof EmpleosRepositorRoute
  EmpleosTecnicoPcRoute: typeof EmpleosTecnicoPcRoute
  EmpleosIndexRoute: typeof EmpleosIndexRoute
}

const EmpleosRouteChildren: EmpleosRouteChildren = {
  EmpleosLimpiezaRoute: EmpleosLimpiezaRoute,
  EmpleosOperadorRoute: EmpleosOperadorRoute,
  EmpleosRepositorRoute: EmpleosRepositorRoute,
  EmpleosTecnicoPcRoute: EmpleosTecnicoPcRoute,
  EmpleosIndexRoute: EmpleosIndexRoute,
}

const EmpleosRouteWithChildren =
  EmpleosRoute._addFileChildren(EmpleosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CargarCvRoute: CargarCvRoute,
  ContactanosRoute: ContactanosRoute,
  CrearCvRoute: CrearCvRoute,
  EmpleosRoute: EmpleosRouteWithChildren,
  LoginRoute: LoginRoute,
  PuestosGuardadosRoute: PuestosGuardadosRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
